### PR TITLE
Lab 7 

### PR DESCRIPTION
**Pull request by sonerkuyar**
We've also discussed domain specific features of our project and how to end the project up till MVP with @ahmetfirat23 , @yusufaygun , @ounuvar and @ozankaymak

### CODE REVIEW

**Comment by ahmetfirat23** [comment]
I have contributed planning phase with #310  and #309

**Comment by ozankaymak** [comment]
I have opened #308 and #311 related to mobile development. Contributed to the discussion related to planning for the milestone next week

**Comment by ounuvar** [comment]
I have opened https://github.com/bounswe/bounswe2024group12/issues/312 and https://github.com/bounswe/bounswe2024group12/issues/313 related to mobile development. Contributed to the discussion related to planning for the milestone next week

**Comment by sonerkuyar** [comment]
I've contributed to planing phase with #315 and #316.

**Comment by yusufaygun** [comment]
I have contributed to planning phase with https://github.com/bounswe/bounswe2024group12/issues/317.

**Pull request merged**
